[package]
name = "rust_test_lib"
version = "0.1.0"
authors = ["Андрей Хомяков <and.hom@gmail.com>"]

[dependencies]
serde = "1.0.27"
serde_derive = "1.0.27"
bincode = "1.0.0"
log = "0.4.1"

rustless = "0.10.0"
hyper = "0.9"
iron = "0.4"
valico = "1"
rustc-serialize = "0.3"